### ISSUE TITLE
Distance detection that indicates spacing to lead vehicle

### ISSUE THREAD

**Issue by nole87** [mapbox/vision-ios-examples#136]
## Description
I find on android vision repo, there is distance detection that indicates spacing to lead vehicle. Does vision sdk for iOS can do the same?

**Comment by chezzdev** [comment]
Hey, @nole87. If you'd like to know the distance to cars in front of you, I'd recommend using [WorldDescription]() object that you can retrieve from the [appropriate method of VisionManagerDelegate](https://docs.mapbox.com/ios/api/vision/vision/0.12.0/Protocols/VisionManagerDelegate.html#/s:12MapboxVision0B15ManagerDelegateP06visionC0_25didUpdateWorldDescriptionyAA0bC8Protocol_p_So08MBVWorldI0CtF). 
From the position of a particular [WorldObject](https://docs.mapbox.com/ios/api/vision/vision/0.12.0/Classes/WorldObject.html#/) you can calculate the distance to that object.

If you still need to estimate the distance by converting from screen to world space, please check out our [POI rendering tutorial](https://docs.mapbox.com/help/tutorials/ios-vision-poi-drawing/) which explains the concept of different coordinate systems and how to convert between them.

**Comment by vladzima** [comment]
Closing this for now. Please reopen if needed.
