### ISSUE TITLE
AR Routing Screen Shows only black screen with user location indicator.

### ISSUE THREAD

**Issue by xyzbilal** [mapbox/vision-ios-examples#141]
Hi, I  downloaded and and installed packages according to instructions. I entered my token to info.plist trying to run app and there is no error. but AR routing screen doesnt show map. only black screen with my location, instruction and Go button. 
any idea how to solve the problem.

**Comment by chezzdev** [comment]
Hi, @xyzbilal. Please check your Internet connection and Mapbox token again.

**Comment by xyzbilal** [comment]
I solved the problem

**Comment by Tabrez10XDev** [comment]
Hello @xyzbilal can you tell how you solved it
