### ISSUE TITLE
Any possibility to paint lane and alert for lane departure?

### ISSUE THREAD

**Issue by xyzbilal** [mapbox/vision-ios-examples#146]
This is not issue but question?
is there any support that we can create alert if car departs from lane and any support we can paint with color the lane with like the app at this link?
[https://apps.apple.com/us/app/augmented-driving/id366841514](url)

**Comment by chezzdev** [comment]
@xyzbilal sure. Acquire the current [Lane](https://docs.mapbox.com/ios/api/vision/vision/0.12.0/Classes/Lane.html#/) instance from [RoadDescription](https://docs.mapbox.com/ios/api/vision/vision/0.12.0/Classes/WorldDescription.html) object and use converters from the world to screen spaces to draw the lane on the screen.

As for the lane departure, the good starting point is the same `RoadDescription` object: you can base your departure logic on the data about the lanes and other road conditions.

**Comment by chezzdev** [comment]
Closing the issue as stale. Feel free to reopen it or create a new issue with your feedback.
