### ISSUE TITLE
doesnt work on xcode 12.2

### ISSUE THREAD

**Issue by masaldana2** [mapbox/vision-ios-examples#153]
- [ ] I have read and followed all the instructions provided in the [README.md](https://github.com/mapbox/vision-ios-examples/blob/master/README.md).

## Steps To Reproduce

1. Click on '....'
1. See error

## Actual behavior

A clear and concise description of what you have experienced instead.

## Configuration

 - Device: [e.g. iPhone8]
 - OS: [e.g. iOS11.2]
 - TestFlight version (if applicable): [e.g. 0.0.1 (22)]
 - `Cartfile.resolved` (if build from source):
```
Put the contents of the Cartfile.resolved here
!!! STRIP YOUR MAPBOX TOKEN !!!
```

**Comment by chezzdev** [comment]
Please see the solution in https://github.com/mapbox/vision-ios-examples/issues/154#issuecomment-732024527.
