### ISSUE TITLE
carthage update fails and cannot build example

### ISSUE THREAD

**Issue by tsuz** [mapbox/vision-ios-examples#154]
- [x] I have read and followed all the instructions provided in the [README.md](https://github.com/mapbox/vision-ios-examples/blob/master/README.md).

## Description

`carthage update --platform ios` fails. This prevents from running this example.

<details>
 <summary>Log</summary>

```

➜  vision-ios-examples git:(master) ✗ carthage update --platform ios
*** Fetching MapboxDirections.swift
*** Downloading binary-only framework Crashlytics at "https://building42.github.io/Specs/Carthage/iOS/Crashlytics.json"
*** Fetching mapbox-navigation-ios
*** Downloading binary-only framework Fabric at "https://building42.github.io/Specs/Carthage/iOS/Fabric.json"
*** Fetching mapbox-vision-ios
*** Downloading binary-only framework mapbox-vision-native-all.carthage at "https://api.mapbox.com/downloads/v1/vision/ios/mapbox-vision-native-all.carthage?access_token=sk.XXXXXX"
*** Downloading binary-only framework opencv at "https://www.mapbox.com/ios-sdk/opencv.json"
*** Fetching Polyline
*** Fetching mapbox-events-ios
*** Downloading binary-only framework MapboxAccounts at "https://www.mapbox.com/ios-sdk/MapboxAccounts.json"
*** Fetching ZIPFoundation
*** Fetching turf-swift
*** Downloading binary-only framework MapboxNavigationNative at "https://www.mapbox.com/ios-sdk/MapboxNavigationNative.json"
*** Fetching Solar
*** Downloading binary-only framework Mapbox-iOS-SDK at "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json"
*** Fetching mapbox-speech-swift
*** Checking out mapbox-vision-ios at "v0.13.1"
*** Checking out ZIPFoundation at "0.9.11"
*** Checking out Polyline at "v4.2.1"
*** Checking out mapbox-speech-swift at "v0.1.1"
*** Checking out turf-swift at "v0.3.0"
*** Checking out Solar at "2.1.0"
*** Checking out mapbox-navigation-ios at "v0.37.2"
*** Checking out MapboxDirections.swift at "v0.30.0"
*** Checking out mapbox-events-ios at "v0.9.5"
*** xcodebuild output can be found in /var/folders/45/x1spyr1x0515cp88vrmn1mgc0000gn/T/carthage-xcodebuild.gdPX5m.log
*** Downloading binary-only framework Crashlytics at "https://building42.github.io/Specs/Carthage/iOS/Crashlytics.json"
*** Downloading binary-only framework Fabric at "https://building42.github.io/Specs/Carthage/iOS/Fabric.json"
*** Downloading binary-only framework Mapbox-iOS-SDK at "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json"
*** Downloading mapbox-events-ios.framework binary at "v0.9.5"
*** Downloading binary-only framework mapbox-vision-native-all.carthage at "https://api.mapbox.com/downloads/v1/vision/ios/mapbox-vision-native-all.carthage?access_token=sk.XXXXXX"
*** Downloading binary-only framework MapboxAccounts at "https://www.mapbox.com/ios-sdk/MapboxAccounts.json"
*** Downloading binary-only framework MapboxNavigationNative at "https://www.mapbox.com/ios-sdk/MapboxNavigationNative.json"
*** Downloading binary-only framework opencv at "https://www.mapbox.com/ios-sdk/opencv.json"
*** Building scheme "MapboxMobileEvents" in MapboxMobileEvents.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/takutosuzuki/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/mapbox-events-ios/v0.9.5/Build/Intermediates.noindex/ArchiveIntermediates/MapboxMobileEvents/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/MapboxMobileEvents.framework/MapboxMobileEvents /Users/takutosuzuki/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/mapbox-events-ios/v0.9.5/Build/Products/Release-iphonesimulator/MapboxMobileEvents.framework/MapboxMobileEvents -output /Users/takutosuzuki/Documents/projects/vision-ios-examples/Carthage/Build/iOS/MapboxMobileEvents.framework/MapboxMobileEvents

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/45/x1spyr1x0515cp88vrmn1mgc0000gn/T/carthage-xcodebuild.gdPX5m.log
```
</details>

## Steps To Reproduce

1. Checkout this repository
2. Follow the readme
3. `carthage update --platform ios` fails

## Expected behavior

Carthage update should not fail.

## Actual behavior

Carthage update fails.

## Configuration

 - Device: n/a
 - OS: 
 - XCode: Version 12.0 (12A7209)
 - TestFlight version (if applicable): [e.g. 0.0.1 (22)]
 - `Cartfile.resolved` (if build from source):
```
Put the contents of the Cartfile.resolved here
!!! STRIP YOUR MAPBOX TOKEN !!!
```

<details>
<summary>Carthage.resolved</summary>

```
binary "https://api.mapbox.com/downloads/v1/vision/ios/mapbox-vision-native-all.carthage?access_token=sk.XXX" "0.13.1"
binary "https://building42.github.io/Specs/Carthage/iOS/Crashlytics.json" "3.14.0"
binary "https://building42.github.io/Specs/Carthage/iOS/Fabric.json" "1.10.2"
binary "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json" "5.5.0"
binary "https://www.mapbox.com/ios-sdk/MapboxAccounts.json" "2.3.0"
binary "https://www.mapbox.com/ios-sdk/MapboxNavigationNative.json" "6.2.1"
binary "https://www.mapbox.com/ios-sdk/opencv.json" "2.4.13"
github "ceeK/Solar" "2.1.0"
github "mapbox/MapboxDirections.swift" "v0.30.0"
github "mapbox/mapbox-events-ios" "v0.9.5"
github "mapbox/mapbox-navigation-ios" "v0.37.2"
github "mapbox/mapbox-speech-swift" "v0.1.1"
github "mapbox/mapbox-vision-ios" "v0.13.1"
github "mapbox/turf-swift" "v0.3.0"
github "raphaelmor/Polyline" "v4.2.1"
github "weichsel/ZIPFoundation" "0.9.11"
```

</details>

**Comment by chezzdev** [comment]
This is [a known Carthage issue](https://github.com/Carthage/Carthage/issues/3019). Please use [a workaround](https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md), provided by Carthage.

**Comment by YohanBaillot** [comment]
This issue should be re-opened. The specific error happening is this one. The mentioned page for the fix does not show a specific fix and the last post show the same issue with Lipo not discussed as a fix

carthage update --platform iOS
*** Downloading binary-only framework MapboxAccounts at "https://www.mapbox.com/ios-sdk/MapboxAccounts.json"
*** Fetching ZIPFoundation
*** Downloading binary-only framework opencv at "https://www.mapbox.com/ios-sdk/opencv.json"
*** Fetching mapbox-events-ios
*** Checking out mapbox-events-ios at "v0.10.7"
*** Checking out ZIPFoundation at "0.9.11"
*** Downloading binary-only framework MapboxAccounts at "https://www.mapbox.com/ios-sdk/MapboxAccounts.json"
*** Downloading binary-only framework opencv at "https://www.mapbox.com/ios-sdk/opencv.json"
*** xcodebuild output can be found in /var/folders/xf/hzf4vsmj7dl1py6t7xgpkq_00000gn/T/carthage-xcodebuild.Y6tKKy.log
*** Building scheme "MapboxMobileEvents" in MapboxMobileEvents.xcodeproj
*** Building scheme "ZIPFoundation" in ZIPFoundation.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/Yohan/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0.1_12A7300/ZIPFoundation/0.9.11/Build/Intermediates.noindex/ArchiveIntermediates/ZIPFoundation/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/ZIPFoundation.framework/ZIPFoundation /Users/Yohan/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0.1_12A7300/ZIPFoundation/0.9.11/Build/Products/Release-iphonesimulator/ZIPFoundation.framework/ZIPFoundation -output /Users/Yohan/Development/Mapbox/MapboxVisionIOS/Carthage/Build/iOS/ZIPFoundation.framework/ZIPFoundation

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/xf/hzf4vsmj7dl1py6t7xgpkq_00000gn/T/carthage-xcodebuild.Y6tKKy.log

**Comment by chezzdev** [comment]
@YohanBaillot right, the correct link to the workaround is [here](https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md). I've edited the previous comment with the appropriate link.

**Comment by tsuz** [comment]
@chezzdev 

Interesting, I tried using both the workarounds below, but I still get the same error

https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md

https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323

Even after I clear the cache using

```
rm -rf ~/Library/Developer/Xcode/DerivedData  
```

I still get this error:

```
/usr/bin/xcrun xcodebuild -project /Users/takutosuzuki/Documents/projects/vision-ios-examples/Carthage/Checkouts/mapbox-vision-ios/MapboxVision.xcodeproj 
-scheme MapboxVision -configuration Release 
-derivedDataPath /Users/takutosuzuki/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/mapbox-vision-ios/v0.14.0 
-sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= 
CARTHAGE=YES archive -archivePath /var/folders/45/x1spyr1x0515cp88vrmn1mgc0000gn/T/mapbox-vision-ios SKIP_INSTALL=YES 
GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO 
STRIP_INSTALLED_PRODUCT=NO
 (launched in /Users/takutosuzuki/Documents/projects/vision-ios-examples/Carthage/Checkouts/mapbox-vision-ios)
```


Do you have any other tips?

**Comment by tsuz** [comment]
In addition to [these instructions](https://github.com/mapbox/vision-ios-examples#tokens), there are several issues to make sure:

### Carthage file

Based on https://github.com/mapbox/vision-ios-examples/issues/154#issuecomment-732024527 , my carthage file looks like this.

<summary>carthage.sh</summary>

<details>

```
# carthage.sh
# Usage example: ./carthage.sh build --platform iOS

set -euo pipefail

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

# For Xcode 12 make sure EXCLUDED_ARCHS is set to arm architectures otherwise
# the build will fail on lipo due to duplicate architectures.

CURRENT_XCODE_VERSION=$(xcodebuild -version | grep "Build version" | cut -d' ' -f3)
echo "EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_$CURRENT_XCODE_VERSION = arm64 arm64e armv7 armv7s armv6 armv8" >> $xcconfig

echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_$(XCODE_PRODUCT_BUILD_VERSION))' >> $xcconfig
echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"
carthage "$@"
```

</details>

### Fetching dependencies


> End-of-central-directory signature not found.  Either this file is not a zipfile, or it constitutes one disk of a multi-part archive.  In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive. unzip:  cannot find zipfile directory in one of...

This is because the module was not obtained from the network based on the Cartfile, usually as a result of module not found or unauthorized (i.e. `.netrc` not being read). I resolved this for my case by adding `--use-netrc` so `./carthage.sh  update --platform ios --use-netrc`. This resolved some modules but not for MapboxVisionNative, but if you run to get the mapbox vision module json via `curl`, then I can see there was no unauthorization issue for me.

```
curl https://api.mapbox.com/downloads/v1/vision/ios/mapbox-vision-native-all.carthage?access_token=<sk.token>
```
returns correct mapping, and accessing the value for `0.13.1` allow for download. (This link can expire very quickly)

However, as per https://github.com/Carthage/Carthage/issues/3180 it fails on Carthage 0.38 so I downgraded to Carthage 0.37 via [this](https://github.com/Homebrew/homebrew-core/commit/5be583636e486fb694c9b84d0783265002685394) and [this](https://github.com/jhen0409/react-native-debugger/issues/567#issuecomment-759419612) .

FWIW, there could be a cache issue so removing cache can be helpful.
```
rm -rf Carthage &&                                                         
rm -rf ~/Library/Caches/carthage &&
rm -rf ~/Library/Caches/org.carthage.CarthageKit
```

### Lower ZipFoundation dependency

Fetching the dependencies are now ok; now I faced some build issues. 

```
 error: compiling for iOS 11.2, but module 'ZIPFoundation' has a minimum deployment target of iOS 12.0: /Users/takutosuzuki/Documents/projects/vision-ios-examples/Carthage/Checkouts/mapbox-vision-ios/Carthage/Build/iOS/ZIPFoundation.framework/Modules/ZIPFoundation.swiftmodule/arm64-apple-ios.swiftmodule
import ZIPFoundation
```

[MapboxVision targets 11.2](https://github.com/mapbox/mapbox-vision-ios/blob/f682922581f5e1198a602721b1f497a2405be655/MapboxVision.podspec#L19) while [`github "weichsel/ZIPFoundation" == 0.9.12` points to iOS 12.0](https://github.com/weichsel/ZIPFoundation/blob/0.9.12/ZIPFoundation.podspec#L12). This is resolved by setting 

**Cartfile**
```
github "weichsel/ZIPFoundation" == 0.9.11
```

and possibly

**Cartfile.resolved**
```
github "weichsel/ZIPFoundation" "0.9.11"
```


And the build is complete 🎉 

![Screen Shot 2021-08-30 at 17 33 08](https://user-images.githubusercontent.com/6927131/131310766-d8830169-57ca-4a43-a69c-b4cea3058f49.png)

**Comment by mailliwi** [comment]
A million thanks @tsuz 🚀🚀🚀
I'm only a junior and it took me forever to figure out everything that was explained in your post, but got to the end eventually.
Just done testing everything and couldn't be happier. Onto my use of it for my personal project now.
You're the best! 😄
