### ISSUE TITLE
Missing Images.swift and Strings.swift file in generated folder?

### ISSUE THREAD

**Issue by Parameshvadivel** [mapbox/vision-ios-examples#31]

**Comment by chezzdev** [comment]
Hey, @Parameshvadivel. Have you installed the dependencies that are mentioned in the README?

**Comment by Parameshvadivel** [comment]
@chezzdev i have used cocopods instead of carthage. My podfile contains
`platform :ios, '11.2'

target 'demo' do
  use_frameworks!

  pod 'MapboxVision', '~> 0.0.1-alpha.4.2'
  pod 'MapboxVisionAR', '~> 0.0.1-alpha.4.2'
  pod 'Mapbox-iOS-SDK', '~> 4.4'
  pod 'MapboxNavigation'
  pod 'Fabric'
  pod 'Crashlytics'
end
`

**Comment by chezzdev** [comment]
For images and strings to be generated `SwiftGen` should be installed. Please take a look at our readme.

**Comment by Parameshvadivel** [comment]
ok thanks
