### ISSUE TITLE
Unable to clone

### ISSUE THREAD

**Issue by goravgrover** [mapbox/vision-ios-examples#54]
These steps doesn't work .

git clone git@github.com:mapbox/vision-ios-examples.git
cd vision-ios-examples
carthage bootstrap --platform ios
open demo.xcodeproj
Sign up or log in to your Mapbox account and grab a Mapbox access token
Enter your Mapbox access token into the value of the MGLMapboxAccessToken key within the Info.plist file
Run the application

I am getting the error
Cloning into 'vision-ios-examples'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

please let me know the solution

**Comment by ksrawat** [comment]
> These steps doesn't work .
> 
> git clone [git@github.com](mailto:git@github.com):mapbox/vision-ios-examples.git
> cd vision-ios-examples
> carthage bootstrap --platform ios
> open demo.xcodeproj
> Sign up or log in to your Mapbox account and grab a Mapbox access token
> Enter your Mapbox access token into the value of the MGLMapboxAccessToken key within the Info.plist file
> Run the application
> 
> I am getting the error
> Cloning into 'vision-ios-examples'...
> [git@github.com](mailto:git@github.com): Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> please let me know the solution

@goravgrover Please use the following command to clone:
`git clone https://github.com/mapbox/vision-ios-examples.git`

**Comment by chezzdev** [comment]
Thanks for posting an issue. 
Installation instructions have been updated. Take a look at it in the [current README.md](https://github.com/mapbox/vision-ios-examples/blob/master/README.md).
