### ISSUE TITLE
Downloading binary-only framework MapboxVisionCore at "https://www.mapbox.com/ios-sdk/MapboxVisionCore.json" Failed to read file or folder at /mapbox-gl-native/ios/builds/mapbox-ios-sdk-4.8.0-dynamic.zip: Error Domain=Result.AnyError Code=1 "The request timed out."

### ISSUE THREAD

**Issue by fusen-github** [mapbox/vision-ios-examples#55]
Downloading binary-only framework MapboxVisionCore at "https://www.mapbox.com/ios-sdk/MapboxVisionCore.json"
Failed to read file or folder at /mapbox-gl-native/ios/builds/mapbox-ios-sdk-4.8.0-dynamic.zip: Error Domain=Result.AnyError Code=1 "The request timed out."

**Comment by chezzdev** [comment]
Thanks for posting an issue. 
Installation instructions have been updated. Take a look at it in the [current README.md](https://github.com/mapbox/vision-ios-examples/blob/master/README.md).
