### ISSUE TITLE
Downloading binary-only framework MapboxVisionCore at "https://www.mapbox.com/ios-sdk/MapboxVisionCore.json" No available version for binary "https://www.mapbox.com/ios-sdk/MapboxVisionCore.json" satisfies the requirement: == 0.2.0

### ISSUE THREAD

**Issue by fusen-github** [mapbox/vision-ios-examples#56]
Downloading binary-only framework MapboxVisionCore at "https://www.mapbox.com/ios-sdk/MapboxVisionCore.json"
No available version for binary "https://www.mapbox.com/ios-sdk/MapboxVisionCore.json" satisfies the requirement: == 0.2.0

**Comment by askquickly** [comment]
We resolved this by removing the carthart.resolve file and then trying the install again

**Comment by chezzdev** [comment]
Thanks for posting an issue. 
Installation instructions have been updated. Take a look at it in the [current README.md](https://github.com/mapbox/vision-ios-examples/blob/master/README.md).
