### ISSUE TITLE
Remove obsolete LaneDepartureState usages

### ISSUE THREAD

**Issue by chezzdev** [mapbox/vision-ios-examples#59]
## Description
`LaneDepartureState` is an obsolete type and will be removed in the future release.

## Goal
Clean up usages of this type.

**Comment by vladzima** [comment]
Apply priority label.

**Comment by vladzima** [comment]
(You have to create label on github first. Labels is one thing that you can't create from zenhub.)

**Comment by chezzdev** [comment]
Closed with #65
