### ISSUE TITLE
Command CompileSwiftSources failed with a nonzero exit code

### ISSUE THREAD

**Issue by ksrawat** [mapbox/vision-ios-examples#64]
- [ ] I have read and followed all the instructions provided in the [README.md](https://github.com/mapbox/vision-ios-examples/blob/master/README.md).

## Steps To Reproduce

I cloned the repo and followed exactly same instructions
## Expected behavior
Should run

## Actual behavior
Command CompileSwiftSources failed with a nonzero exit code

## Configuration

 - Device: [e.g. iPhone8]
 - OS: [e.g. iOS11.2]
 - TestFlight version (if applicable) [e.g. 0.0.1 (22)]
 - `Cartfile.resolved` (if build from source):
```
Put the contents of the Cartfile.resolved here
!!! STRIP YOUR MAPBOX TOKEN !!!
```

**Comment by chezzdev** [comment]
Hello, @ksrawat.
Could you please go through the issue and provide more details in "Steps to reproduce" specifying steps that you've followed and the particular step where the error occurs and also "Configuration" to get an understanding which setup do you have.

**Comment by pablolb94** [comment]
I'm having the same problem, I get the error in: generated/images.swift and /generated/strings.swift, this said that not exits this files, what i can do?

**Comment by chezzdev** [comment]
Closing the issue as stale. Feel free to reopen it once you have more details.
