### ISSUE TITLE
Update welcome message and links to TOS and Privacy Policy

### ISSUE THREAD

**Issue by chezzdev** [mapbox/vision-ios-examples#69]
## Description
Welcome message should be updated with the following text:
_I agree to the Mapbox Terms of Service and Privacy Policy_

*Terms of Service* link : https://www.mapbox.com/tos/
*Privacy* link : https://www.mapbox.com/privacy/

## Goal
Remove reference to old agreement and specify provide just links to TOS and PP.

## Steps
- [x] Adjust design for welcome and info screen with @rokkeds 
- [x] Implement in UI
- [x] Remove agreement pdf from resources

**Comment by IodaMikeMapbox** [comment]
Design https://app.zeplin.io/project/5cecfe8a32999a29aba37979
