### ISSUE TITLE
Support UK signs in demo application

### ISSUE THREAD

**Issue by dersim-davaod** [mapbox/vision-ios-examples#74]
## Description
We added support for UK signs in https://github.com/mapbox/mapbox-vision/pull/976.
Need to support changes in our demo app.

**NOTE:** Wait until appropriate changes are made in scope of mapbox/mapbox-vision#1092
**NOTE:** Should be merged after https://github.com/mapbox/mapbox-vision-ios/issues/108

## Goal
The goal is to make stable `dev` branch.

## Steps
- [x] Import new signs (@LinaShiryaeva/ @rokkeds) @rokkeds thinks we can have assets next week (05/27-05/31)
- [x] Generate file with resources
- [x] Decide what are correct signs for other country
- [x] Support UK signs (make sure to reimplement and remove `// FIXME :` introduced in https://github.com/mapbox/vision-ios-examples/pull/77)
- [x] Tested and acceptance criteria is matched (result matches the goal)

**Comment by dersim-davaod** [comment]
Fake support implemented, wait for classifiers, as soon as it will be released, task will be processed.

**Comment by dersim-davaod** [comment]
Wait until appropriate changes are made in scope of mapbox/mapbox-vision#1092

**Comment by rokkeds** [comment]
Europe + unique UK signs assets can be found here: https://www.dropbox.com/sh/8cipaqe3iijvwso/AADJ8D8tz_fZh2bY5Hx27vv6a?dl=0
