### ISSUE TITLE
Simplify massive enums for sign assets chooser

### ISSUE THREAD

**Issue by IodaMikeMapbox** [mapbox/vision-ios-examples#87]
It is hard to maintain `Signs` class with all the assets images, I think we could write smart enough code to get rid of maintain it manually or at least make it simpler by providing dictionaries of assets and the file will become three times smaller. For now the code contains heavy boilerplate and a lot of copy/paste code

**Comment by dersim-davaod** [comment]
A subtask for mapbox/mapbox-vision-ios#122

**Comment by chezzdev** [comment]
Closing as a duplicate of https://github.com/mapbox/vision-ios-examples/issues/131
